# Generated by Django 5.2.8 on 2025-12-22 07:44

import bookings.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined')], default='pending', help_text='Current status of the booking', max_length=20)),
                ('preferred_date', models.DateField(help_text="Customer's preferred service date")),
                ('preferred_time', models.TimeField(help_text="Customer's preferred service time")),
                ('scheduled_date', models.DateField(blank=True, help_text='Confirmed scheduled date (set by provider)', null=True)),
                ('scheduled_time', models.TimeField(blank=True, help_text='Confirmed scheduled time (set by provider)', null=True)),
                ('service_address', models.CharField(help_text='Full address where service will be performed', max_length=255)),
                ('service_city', models.CharField(help_text='City', max_length=100)),
                ('service_district', models.CharField(blank=True, help_text='District', max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, help_text='Location latitude for map', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Location longitude for map', null=True)),
                ('description', models.TextField(help_text="Customer's description of the problem/requirement")),
                ('special_instructions', models.TextField(blank=True, help_text="Any special instructions (e.g., 'Call before arriving', 'Park on street')", null=True)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, help_text="Provider's quoted price in NRS (may differ from base price)", max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, help_text='Final agreed price in NRS after any adjustments', max_digits=10, null=True)),
                ('customer_phone', models.CharField(help_text='Customer contact number for this booking', max_length=15)),
                ('customer_name', models.CharField(help_text='Customer name (snapshot for this booking)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the booking was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When provider accepted the booking', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the service was completed', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the booking was cancelled', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation', null=True)),
                ('provider_notes', models.TextField(blank=True, help_text='Internal notes by provider (not visible to customer)', null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='Who cancelled the booking (customer or provider)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer who made the booking', limit_choices_to={'user_type': 'find'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_bookings', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(help_text='Service provider assigned to this booking', limit_choices_to={'user_type': 'offer'}, on_delete=django.db.models.deletion.CASCADE, related_name='provider_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Photo of the service area/items', upload_to=bookings.models.booking_image_path)),
                ('image_type', models.CharField(choices=[('before', 'Before Service'), ('during', 'During Service'), ('after', 'After Service')], help_text='When this photo was taken (before/during/after)', max_length=10)),
                ('description', models.CharField(blank=True, help_text="Optional description of what's shown in the image", max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When the image was uploaded')),
                ('booking', models.ForeignKey(help_text='The booking this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bookings.booking')),
                ('uploaded_by', models.ForeignKey(help_text='Who uploaded this image (customer or provider)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_booking_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Image',
                'verbose_name_plural': 'Booking Images',
                'ordering': ['image_type', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Service name (e.g., 'Emergency Plumbing Repair')", max_length=200)),
                ('description', models.TextField(help_text="Detailed description of what's included in this service")),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price in NRS (e.g., 1500.00)', max_digits=10)),
                ('price_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Per Hour'), ('negotiable', 'Negotiable')], default='fixed', help_text='How the service is priced', max_length=20)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum charge for this service (e.g., travel fee, call-out fee). Customer pays at least this amount even if service costs less.', max_digits=10)),
                ('estimated_duration', models.PositiveIntegerField(blank=True, help_text='Estimated duration in minutes (e.g., 60 for 1 hour)', null=True)),
                ('service_radius', models.PositiveIntegerField(blank=True, help_text="Service area radius in kilometers from provider's location. Leave blank for unlimited or use provider's service_area.", null=True)),
                ('requires_site_visit', models.BooleanField(default=False, help_text='Whether the provider needs to visit the site before giving a final quote')),
                ('emergency_service', models.BooleanField(default=False, help_text='Whether this is an emergency/24-7 service (may have higher rates)')),
                ('additional_charges_note', models.TextField(blank=True, help_text="Notes about additional charges (e.g., 'Materials not included', 'Extra charge for weekends', 'Parking fees may apply')", null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service is currently being offered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(help_text='The service provider offering this service', limit_choices_to={'user_type': 'offer'}, on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
                ('specialization', models.ForeignKey(help_text='The specialization category this service falls under', on_delete=django.db.models.deletion.PROTECT, related_name='services', to='users.specialization')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-created_at'],
                'unique_together': {('provider', 'title')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(help_text='The service being booked', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.service'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total payment amount in NRS', max_digits=10)),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='Platform commission percentage (e.g., 10.00 for 10%)', max_digits=5)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Platform commission/fee in NRS (calculated from percentage)', max_digits=10)),
                ('provider_amount', models.DecimalField(decimal_places=2, help_text='Amount provider receives after platform fee in NRS', max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('esewa', 'eSewa'), ('khalti', 'Khalti')], help_text='How the customer is paying', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', help_text='Current payment status', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID from payment gateway (eSewa, Khalti, etc.)', max_length=100, null=True, unique=True)),
                ('reference_number', models.CharField(blank=True, help_text='Reference number for bank transfers or receipts', max_length=100, null=True)),
                ('gateway_response', models.JSONField(blank=True, help_text='Raw response from payment gateway (for debugging)', null=True)),
                ('payment_notes', models.TextField(blank=True, help_text='Additional notes about this payment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When payment record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('paid_at', models.DateTimeField(blank=True, help_text='When payment was completed', null=True)),
                ('refunded_at', models.DateTimeField(blank=True, help_text='When payment was refunded (if applicable)', null=True)),
                ('refund_reason', models.TextField(blank=True, help_text='Reason for refund', null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount refunded in NRS (may be partial)', max_digits=10, null=True)),
                ('booking', models.OneToOneField(help_text='The booking this payment is for', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking')),
                ('customer', models.ForeignKey(help_text='Customer who is making the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(help_text='Provider who will receive the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='bookings_pa_status_39a882_idx'), models.Index(fields=['customer', '-created_at'], name='bookings_pa_custome_f00387_idx'), models.Index(fields=['provider', '-created_at'], name='bookings_pa_provide_a2e339_idx'), models.Index(fields=['transaction_id'], name='bookings_pa_transac_fdc55d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Star rating from 1 (worst) to 5 (best)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, help_text="Optional short title (e.g., 'Great service!')", max_length=200)),
                ('comment', models.TextField(blank=True, help_text='Detailed feedback about the service')),
                ('would_recommend', models.BooleanField(default=True, help_text='Whether the customer would recommend this provider')),
                ('provider_response', models.TextField(blank=True, help_text="Provider's public response to the review")),
                ('responded_at', models.DateTimeField(blank=True, help_text='When the provider responded', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(help_text='The completed booking this review refers to', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking')),
                ('customer', models.ForeignKey(help_text='Customer who wrote the review', limit_choices_to={'user_type': 'find'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(help_text='Provider who received the review', limit_choices_to={'user_type': 'offer'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', '-created_at'], name='bookings_re_provide_ce5500_idx'), models.Index(fields=['customer', '-created_at'], name='bookings_re_custome_1b59a2_idx'), models.Index(fields=['rating'], name='bookings_re_rating_a9b587_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', '-created_at'], name='bookings_bo_status_eb4fb1_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', '-created_at'], name='bookings_bo_custome_10bd54_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['provider', '-created_at'], name='bookings_bo_provide_7ad8bb_idx'),
        ),
    ]
