# Generated by Django 5.2.8 on 2026-01-27 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='Who cancelled the booking (customer or provider)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(help_text='Customer who made the booking', limit_choices_to={'user_type': 'find'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider',
            field=models.ForeignKey(help_text='Service provider assigned to this booking', limit_choices_to={'user_type': 'offer'}, on_delete=django.db.models.deletion.CASCADE, related_name='provider_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingimage',
            name='booking',
            field=models.ForeignKey(help_text='The booking this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingimage',
            name='uploaded_by',
            field=models.ForeignKey(help_text='Who uploaded this image (customer or provider)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_booking_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='booking',
            field=models.ForeignKey(help_text='The booking this service is part of', on_delete=django.db.models.deletion.CASCADE, related_name='booking_services', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(help_text='The booking this payment is for', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(help_text='Customer who is making the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.ForeignKey(help_text='Provider who will receive the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provideravailability',
            name='provider',
            field=models.OneToOneField(help_text="The service provider's availability record", limit_choices_to={'user_type': 'offer'}, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(help_text='The completed booking this review refers to', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(help_text='Customer who wrote the review', limit_choices_to={'user_type': 'find'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='provider',
            field=models.ForeignKey(help_text='Provider who received the review', limit_choices_to={'user_type': 'offer'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(help_text='The service provider offering this service', limit_choices_to={'user_type': 'offer'}, on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='specialization',
            field=models.ForeignKey(help_text='The specialization category this service falls under', on_delete=django.db.models.deletion.PROTECT, related_name='services', to='users.specialization'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='service',
            field=models.ForeignKey(help_text='The service being booked', on_delete=django.db.models.deletion.PROTECT, related_name='booking_service_entries', to='bookings.service'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(help_text='The service being booked', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.service'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='bookings_pa_status_39a882_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer', '-created_at'], name='bookings_pa_custome_f00387_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', '-created_at'], name='bookings_pa_provide_a2e339_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='bookings_pa_transac_fdc55d_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['provider', '-created_at'], name='bookings_re_provide_ce5500_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['customer', '-created_at'], name='bookings_re_custome_1b59a2_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='bookings_re_rating_a9b587_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('provider', 'specialization')},
        ),
        migrations.AlterUniqueTogether(
            name='bookingservice',
            unique_together={('booking', 'service')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', '-created_at'], name='bookings_bo_status_eb4fb1_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', '-created_at'], name='bookings_bo_custome_10bd54_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['provider', '-created_at'], name='bookings_bo_provide_7ad8bb_idx'),
        ),
    ]
