# Generated by Django 5.2.8 on 2025-12-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_provideravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='approval_note',
            field=models.TextField(blank=True, help_text="Customer's approval note", null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='completion_note',
            field=models.TextField(blank=True, help_text="Provider's completion note when marking job done", null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_review_expires_at',
            field=models.DateTimeField(blank=True, help_text="When customer's review window expires for auto-approval", null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='dispute_note',
            field=models.TextField(blank=True, help_text="Customer's additional details about dispute", null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='dispute_reason',
            field=models.TextField(blank=True, help_text="Customer's dispute reason if disputing completion", null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_completed_at',
            field=models.DateTimeField(blank=True, help_text='When provider marked job as completed (uploaded after-photos)', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('provider_completed', 'Provider Completed'), ('awaiting_customer', 'Awaiting Customer'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('declined', 'Declined')], default='pending', help_text='Current status of the booking', max_length=20),
        ),
    ]
