# Generated by Django 5.2.8 on 2026-02-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='approval_note',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_review_expires_at',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('provider_completed', 'Provider Completed'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('declined', 'Declined')], default='pending', help_text='Current status of the booking', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('khalti', 'Khalti')], help_text='How the customer is paying', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Transaction ID from payment gateway (Khalti, etc.)', max_length=100, null=True, unique=True),
        ),
    ]
