# Generated by Django 5.2.8 on 2026-02-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_approval_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmation_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for provider to accept/decline. Auto-expired if not responded by this time.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='expired_at',
            field=models.DateTimeField(blank=True, help_text='When the booking was auto-expired due to no provider response', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('provider_completed', 'Provider Completed'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', help_text='Current status of the booking', max_length=20),
        ),
    ]
