# Generated by Django 5.2.8 on 2025-12-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_approval_note_booking_completion_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingimage',
            name='image_type',
            field=models.CharField(choices=[('before', 'Before Service'), ('during', 'During Service'), ('after', 'After Service'), ('approval_photos', 'Approval Photos')], help_text='When this photo was taken (before/during/after/approval)', max_length=50),
        ),
    ]
