# Generated by Django 5.2.8 on 2026-01-06 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_bookingimage_image_type'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('provider', 'specialization')},
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, default='', help_text="Detailed description of what's included in this service"),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, default='', help_text="Service name (e.g., 'Emergency Plumbing Repair')", max_length=200),
        ),
    ]
