# Generated by Django 5.2.8 on 2026-01-07 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_service_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_booking', models.DecimalField(decimal_places=2, help_text='Base price when this service was added to booking', max_digits=10)),
                ('price_type_at_booking', models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Per Hour'), ('negotiable', 'Negotiable')], default='fixed', help_text='Price type when this service was added to booking', max_length=20)),
                ('minimum_charge_at_booking', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum charge when this service was added to booking', max_digits=10)),
                ('estimated_duration_at_booking', models.PositiveIntegerField(blank=True, help_text='Estimated duration (in minutes) when this service was added to booking', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which services are listed in the booking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(help_text='The booking this service is part of', on_delete=django.db.models.deletion.CASCADE, related_name='booking_services', to='bookings.booking')),
                ('service', models.ForeignKey(help_text='The service being booked', on_delete=django.db.models.deletion.PROTECT, related_name='booking_service_entries', to='bookings.service')),
            ],
            options={
                'verbose_name': 'Booking Service',
                'verbose_name_plural': 'Booking Services',
                'ordering': ['order', 'created_at'],
                'unique_together': {('booking', 'service')},
            },
        ),
    ]
