# Generated by Django 5.2.8 on 2026-01-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_bookingservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingservice',
            name='estimated_duration_at_booking',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated duration (in hours) when this service was added to booking', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='estimated_duration',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated duration in hours (e.g., 1.5 for 1.5 hours, 0.5 for 30 minutes)', max_digits=5, null=True),
        ),
    ]
