# Generated by Django 5.2.8 on 2026-01-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_bookingservice_estimated_duration_at_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='estimated_duration_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum estimated duration in hours', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='estimated_duration_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum estimated duration in hours', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='estimated_duration',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated duration in hours (average of min and max)', max_digits=5, null=True),
        ),
    ]
