# Generated by Django 5.2.8 on 2026-01-17 06:02

from django.db import migrations, models


def cleanup_citizenship_numbers(apps, schema_editor):
    """Clean up citizenship numbers that are longer than 11 characters"""
    User = apps.get_model('users', 'User')
    # Truncate any citizenship numbers longer than 11 characters
    users_with_long_numbers = User.objects.exclude(citizenship_number__isnull=True).exclude(citizenship_number='')
    for user in users_with_long_numbers:
        if len(user.citizenship_number) > 11:
            # Truncate to 11 characters or set to None if invalid
            user.citizenship_number = user.citizenship_number[:11] if user.citizenship_number.isdigit() else None
            user.save(update_fields=['citizenship_number'])


def reverse_cleanup(apps, schema_editor):
    """Reverse migration - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        # First, clean up the data
        migrations.RunPython(cleanup_citizenship_numbers, reverse_cleanup),
        # Then alter the field
        migrations.AlterField(
            model_name='user',
            name='citizenship_number',
            field=models.CharField(blank=True, help_text='Citizenship or national ID number (11 digits)', max_length=11, null=True),
        ),
    ]
