# Generated by Django 5.2.8 on 2025-12-14 06:48

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default.jpg', upload_to=users.models.user_profile_picture_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='service_area',
            field=models.CharField(default='', max_length=255),
        ),
    ]
