# Generated by Django 5.2.8 on 2026-01-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('find', 'Find Services'), ('offer', 'Offer Services'), ('admin', 'Admin')], default='find', max_length=10),
        ),
    ]
