# Generated by Django 5.2.8 on 2026-01-17 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_citizenship_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='citizenship_number',
            field=models.CharField(blank=True, help_text='Citizenship or national ID number (11 digits)', max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Citizenship number must be exactly 11 digits', regex='^\\d{11}$')]),
        ),
    ]
