# Generated by Django 5.2.8 on 2025-12-14 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_address_alter_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Enter 10 digit phone number (e.g., 9812345678)', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Nepal mobile number. Examples: 9812345678, 9712345678, +9779812345678', regex='^(?:\\+977|977)?(97|98)\\d{8}$')]),
        ),
    ]
