# Generated by Django 5.2.8 on 2025-12-17 11:41

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='citizenship_back',
            field=models.ImageField(blank=True, help_text='Back side of citizenship or national ID card', null=True, upload_to=users.models.user_citizenship_path),
        ),
        migrations.AddField(
            model_name='user',
            name='citizenship_front',
            field=models.ImageField(blank=True, help_text='Front side of citizenship or national ID card', null=True, upload_to=users.models.user_citizenship_path),
        ),
        migrations.AddField(
            model_name='user',
            name='citizenship_number',
            field=models.CharField(blank=True, help_text='Citizenship or national ID number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='citizenship_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='clerk_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='firebase_phone_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, help_text='Current location/address', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Enter 10 digit phone number (e.g., 9812345678)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Nepal mobile number. Examples: 9812345678, 9712345678, +9779812345678', regex='^(97|98)\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='service_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
