# Generated by Django 5.2.8 on 2025-12-18 08:07

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_citizenship_back_user_citizenship_front_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter 10 digit phone number (e.g., 9812345678)', max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Nepal mobile number. Examples: 9812345678, 9712345678, +9779812345678', regex='^(97|98)\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture of the user', null=True, upload_to=users.models.user_profile_picture_path),
        ),
    ]
