# Generated by Django 5.2.8 on 2025-12-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_phone_number_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_completed',
            field=models.BooleanField(default=False, help_text='Set to True only after phone verification is complete'),
        ),
    ]
