# Generated by Django 5.2.8 on 2026-01-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_supabase_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clerk_user_id',
            field=models.CharField(blank=True, help_text='Deprecated: Clerk integration ID', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='supabase_uid',
            field=models.CharField(blank=True, help_text='Supabase user UUID (from JWT sub claim)', max_length=255, null=True, unique=True),
        ),
    ]
