# Generated by Django 5.2.8 on 2026-02-02 08:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EsewaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Config name (e.g., 'production', 'test')", max_length=100, unique=True)),
                ('merchant_code', models.CharField(help_text='eSewa merchant code (scd parameter)', max_length=200)),
                ('secret_key', models.CharField(help_text='eSewa secret key for verification', max_length=200)),
                ('is_active', models.BooleanField(default=False, help_text='Currently active configuration')),
                ('is_test_mode', models.BooleanField(default=True, help_text='Test mode or production')),
                ('client_id', models.CharField(blank=True, help_text='eSewa SDK client ID (optional)', max_length=200)),
                ('client_secret', models.CharField(blank=True, help_text='eSewa SDK client secret (optional)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'eSewa Configuration',
                'verbose_name_plural': 'eSewa Configurations',
            },
        ),
        migrations.CreateModel(
            name='KhaltiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Config name (e.g., 'production', 'test')", max_length=100, unique=True)),
                ('public_key', models.CharField(help_text='Khalti public key', max_length=200)),
                ('secret_key', models.CharField(help_text='Khalti secret key', max_length=200)),
                ('is_active', models.BooleanField(default=False, help_text='Currently active configuration')),
                ('is_test_mode', models.BooleanField(default=True, help_text='Test mode or production')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Khalti Configuration',
                'verbose_name_plural': 'Khalti Configurations',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique transaction identifier for our system', unique=True)),
                ('payment_method', models.CharField(choices=[('khalti', 'Khalti'), ('esewa', 'eSewa'), ('cash', 'Cash')], help_text='Payment gateway used', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in NRS', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', help_text='Current transaction status', max_length=20)),
                ('gateway_transaction_id', models.CharField(blank=True, help_text='Transaction ID from payment gateway (Khalti token, eSewa ref, etc.)', max_length=200, null=True)),
                ('gateway_payment_id', models.CharField(blank=True, help_text='Payment ID from gateway (used for verification)', max_length=200, null=True)),
                ('gateway_response', models.JSONField(blank=True, help_text='Raw response from payment gateway', null=True)),
                ('verification_response', models.JSONField(blank=True, help_text='Response from payment verification API', null=True)),
                ('customer_name', models.CharField(blank=True, help_text='Customer name for gateway', max_length=200)),
                ('customer_email', models.EmailField(blank=True, help_text='Customer email for gateway', max_length=254)),
                ('customer_phone', models.CharField(blank=True, help_text='Customer phone for gateway', max_length=15)),
                ('return_url', models.URLField(blank=True, help_text='URL to return after successful payment')),
                ('failure_url', models.URLField(blank=True, help_text='URL to return after failed payment')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount refunded (if applicable)', max_digits=10, null=True)),
                ('refund_reason', models.TextField(blank=True, help_text='Reason for refund')),
                ('refund_reference', models.CharField(blank=True, help_text='Refund reference from gateway', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When transaction was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When payment was completed', null=True)),
                ('refunded_at', models.DateTimeField(blank=True, help_text='When refund was processed', null=True)),
                ('booking', models.ForeignKey(help_text='The booking this transaction is for', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bookings.booking')),
                ('customer', models.ForeignKey(help_text='Customer making the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_uid'], name='payments_tr_transac_5e0570_idx'), models.Index(fields=['gateway_transaction_id'], name='payments_tr_gateway_41c502_idx'), models.Index(fields=['booking', '-created_at'], name='payments_tr_booking_989ae8_idx'), models.Index(fields=['customer', '-created_at'], name='payments_tr_custome_f99334_idx'), models.Index(fields=['status', '-created_at'], name='payments_tr_status_7127e3_idx')],
            },
        ),
    ]
