# Generated by Django 5.2.8 on 2026-02-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, help_text='Transaction ID from payment gateway (Khalti token, etc.)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('khalti', 'Khalti'), ('cash', 'Cash')], help_text='Payment gateway used', max_length=20),
        ),
    ]
