// Comprehensive Nepali cities and districts (augments dynamic backend locations)
export const nepaliCities = [
  'Kathmandu','Lalitpur','Bhaktapur','Pokhara','Bharatpur','Biratnagar','Dharan','Itahari','Birgunj','Hetauda',
  'Butwal','Janakpur','Dhangadhi','Nepalgunj','Ghorahi','Tansen','Birtamode','Damak','Dhulikhel','Banepa',
  'Surkhet','Kirtipur','Madhyapur Thimi','Gokarneshwar','Tokha','Godawari','Chandragiri','Budhanilkantha','Kageshwori Manohara',
  'Kohalpur','Tulasipur','Besisahar','Gorkha','Bandipur','Palpa','Syangja','Parbat','Baglung',
  'Beni','Jomsom','Rajbiraj','Inaruwa','Gaighat','Lahan','Siraha','Malangwa',
  'Kalaiya','Gaur','Jaleshwar','Mahendranagar','Barahathawa','Bardibas','Chandrapur','Ramechhap',
  'Sindhuli','Charikot','Manthali','Okhaldhunga','Salleri','Phidim','Ilam','Taplejung','Panchthar','Dhankuta'
];

export const nepaliDistricts = {
  'Kathmandu': ['Kathmandu'],
  'Lalitpur': ['Lalitpur'],
  'Bhaktapur': ['Bhaktapur'],
  'Pokhara': ['Kaski'],
  'Bharatpur': ['Chitwan'],
  'Biratnagar': ['Morang'],
  'Dharan': ['Sunsari'],
  'Itahari': ['Sunsari'],
  'Birgunj': ['Parsa'],
  'Hetauda': ['Makwanpur'],
  'Butwal': ['Rupandehi'],
  'Janakpur': ['Dhanusha'],
  'Dhangadhi': ['Kailali'],
  'Nepalgunj': ['Banke'],
  'Ghorahi': ['Dang'],
  'Tansen': ['Palpa'],
  'Birtamode': ['Jhapa'],
  'Damak': ['Jhapa'],
  'Dhulikhel': ['Kavrepalanchok'],
  'Banepa': ['Kavrepalanchok'],
  'Surkhet': ['Surkhet'],
  'Kirtipur': ['Kathmandu'],
  'Madhyapur Thimi': ['Bhaktapur'],
  'Gokarneshwar': ['Kathmandu'],
  'Tokha': ['Kathmandu'],
  'Godawari': ['Lalitpur'],
  'Chandragiri': ['Kathmandu'],
  'Budhanilkantha': ['Kathmandu'],
  'Kageshwori Manohara': ['Kathmandu'],
  'Kohalpur': ['Banke'],
  'Tulasipur': ['Dang'],
  'Besisahar': ['Lamjung'],
  'Gorkha': ['Gorkha'],
  'Bandipur': ['Tanahun'],
  'Palpa': ['Palpa'],
  'Syangja': ['Syangja'],
  'Parbat': ['Parbat'],
  'Baglung': ['Baglung'],
  'Beni': ['Myagdi'],
  'Jomsom': ['Mustang'],
  'Rajbiraj': ['Saptari'],
  'Inaruwa': ['Sunsari'],
  'Gaighat': ['Udayapur'],
  'Lahan': ['Siraha'],
  'Siraha': ['Siraha'],
  'Malangwa': ['Sarlahi'],
  'Kalaiya': ['Bara'],
  'Gaur': ['Rautahat'],
  'Jaleshwar': ['Mahottari'],
  'Mahendranagar': ['Kanchanpur'],
  'Barahathawa': ['Sarlahi'],
  'Bardibas': ['Mahottari'],
  'Chandrapur': ['Rautahat'],
  'Ramechhap': ['Ramechhap'],
  'Sindhuli': ['Sindhuli'],
  'Charikot': ['Dolakha'],
  'Manthali': ['Ramechhap'],
  'Okhaldhunga': ['Okhaldhunga'],
  'Salleri': ['Solukhumbu'],
  'Phidim': ['Panchthar'],
  'Ilam': ['Ilam'],
  'Taplejung': ['Taplejung'],
  'Panchthar': ['Panchthar'],
  'Dhankuta': ['Dhankuta']
};
